Ruby Capstone - Final Code Review
miguelesco/capstone-m4 pull request #50
Opened 2021-10-26 20:52 UTC by jmontanholi

Here is the presentation video: 

https://user-images.githubusercontent.com/73256642/138959258-9aed8997-c983-4868-ad8c-90f7242af74e.mp4

## In this project my partners and I implemented the following:

* # Classes:
   * ### Book
   * ### Author
   * ### DB
      * #### Methods to save data into JSON and get information back.  
   * ### Game
   * ### Genres
   * ### Item
   * ### Label
   * ### Movie
   * ### Music
   * ### Source

* # Database
   * ### Schema.sql file

* # Module
   * ### All functions used in APP are stored here like these for example:
      *  #### Create_book
      *  #### Show_books

* # App class that runs the UI

![](https://media2.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

2021-10-26 22:35 UTC, Emmyn5600 requested changes
Hi,

Good job so far! 👏🏼 @GuilhermeGiachellin, @ArthurGC , @miguelesco,  and @jmontanholi  

May I highlight the following:
- 5 minutes of video presentation is showing all the features of the project:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- The git-flow has been followed :heavy_check_mark:
- The repo looks professional:heavy_check_mark:
- Some data are being stored in JSON files :heavy_check_mark: 

## STATUS: CHANGES REQUESTED :recycle:


### Changes requested.



- Tests are not passing successfully
![test-2](https://user-images.githubusercontent.com/55635977/138970416-248a4834-c27e-42c3-847b-0835549fccc4.png)
- _Make sure that all tables have all columns corresponding to the proiperties from the class diagram._
- _Check if all foreign keys were set up correctly_.
- _Check if all foreign keys columns have corresponding indexes_.
- _Check the comment under the review_

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-10-26 22:35 UTC, Emmyn5600 commented on src/modules/app_module.rb
> +  end
- [x] When you are creating the book, you need to ask a user the following questions:

- What is the title on the label?
- What is the color of the label?
- What is the source? (ie: a shop, a friend...)
- What genre is it?
- What is the author's first name?
- What is the author's last name?
- When was it published (yyyy-mm-dd)?
- Who is the publisher
- What is the cover state
------------------After created successfully, kindly display the confirmation message `book successfully created!` 

* After getting some answers to the above questions, those answers have to be saved in the json file, so that we can see them later to retrieve some data, for instance, in your application, you included the author's name manually, however, we need to add both First and Last names while we are creating the book as well as label, source, and genre.

* Kindly use, the date format `(yyyy-mm-dd)` to the published date or elsewhere we need to use it.

2021-10-26 22:35 UTC, Emmyn5600 commented on src/modules/app_module.rb
> +    list.each { |author| puts "#{author.first_name} #{author.last_name}" }
- [x] Here, you are listing the authors that were created manually, however, we need to create and list our own authors. Or you can also do this `Select an author from the following list or "a" to add a new author:`

    - You can select the author from the existing one or 
    - Type `a` to add a new one.

2021-10-26 22:35 UTC, Emmyn5600 commented on src/modules/app_module.rb
> +  end
- [x] Even to create a game, you need to ask the above questions and then you will ask the following after this 

    - When was it published (yyyy-mm-dd)?
    - When did you play it for last time (yyyy-mm-dd)?  
    - Is the game multiplayer? (y/n)
    
    ------------------After created successfully, kindly display the confirmation message game successfully created!

2021-10-26 22:35 UTC, Emmyn5600 commented on src/modules/app_module.rb
> +  end
- [x] You either have to `Select a genre from the following list or "a" to add new genre: `

2021-10-26 22:35 UTC, Emmyn5600 commented on src/modules/app_module.rb
> +    end
- [x] Select a label from the following list or "a" to add a new label:

2021-10-26 22:40 UTC, jmontanholi commented
@Emmyn5600  Thanks for the review!! Why isn't any of this in the requirements of the project???

2021-10-26 22:43 UTC, Emmyn5600 commented
@jmontanholi, kindly check again the project requirements as well as ERD you will see that.

2021-10-26 22:44 UTC, jmontanholi commented
@Emmyn5600 yes, very descriptive material 

![image](https://user-images.githubusercontent.com/73256642/138971467-b1c39060-eeac-4410-9380-00712af06c0c.png)

2021-10-26 22:56 UTC, Emmyn5600 commented
So how about the schema? how are you going to implement it?

2021-10-26 22:58 UTC, jmontanholi commented
I really don't understand what you mean. I know this is not your fault, and we are probably just going to do what you suggested, but I'm really mad at Microverse, they always do this, put different things on the project requirements and in the code review guidelines.
![image](https://user-images.githubusercontent.com/73256642/138972714-b61121e4-5856-4b33-b6f4-7cc820357978.png)

2021-10-26 23:08 UTC, jmontanholi commented
sorry @Emmyn5600 , now that I have seen something, shouldn't these requirements be optional???

![image](https://user-images.githubusercontent.com/73256642/138973621-78fd7005-8008-48bf-94a5-bb2b84359e59.png)

2021-10-27 16:07 UTC, mimipeshy commented on src/modules/app_module.rb
> +  end
[OPTIONAL] You can choose to add the extra data in your app. This is not explicitly given in the project guidelines

2021-10-27 16:09 UTC, mimipeshy reviewed
## Hello Team 👋,

_This is an additional review as a result of the second opinion request._

Good job on working on this app, it's very easy to navigate. CR guidelines are always consistent with project requirements, however, errors may arise and we appreciate any feedback on areas we can improve. From this PR, some of the issues the CR has stated are OPTIONAL since they are not explicitly given in the project requirements. I will leave a comment with the OPTIONAL keyword

Kindly submit for another review when done!
Keep rocking 🚀!

2021-10-27 16:11 UTC, mimipeshy commented on src/modules/app_module.rb
> +    list.each { |author| puts "#{author.first_name} #{author.last_name}" }
When I choose option 7, your app crashes kindly check on this
![image](https://user-images.githubusercontent.com/33067256/139104943-47b4cc38-5409-4f94-a9d8-3d2808b548c8.png)

2021-10-27 16:13 UTC, mimipeshy commented on src/modules/app_module.rb
> +  end
- [x] You implemented this, good job ✔️

2021-10-27 16:14 UTC, mimipeshy commented on src/modules/app_module.rb
> +    end
- You implemented this, good job ✔️

2021-10-27 16:15 UTC, mimipeshy commented on src/modules/app_module.rb
> +  end
- You have implemented this, good job ✔️

2021-10-27 16:19 UTC, mimipeshy commented
> I really don't understand what you mean. I know this is not your fault, and we are probably just going to do what you suggested, but I'm really mad at Microverse, they always do this, but different things on the project requirements and in the code review guidelines. ![image](https://user-images.githubusercontent.com/73256642/138972714-b61121e4-5856-4b33-b6f4-7cc820357978.png)

- [x] This was not implemented. Kindly create a schema.sql file that has the following tables: books,music_albums, games, movies (only if the group has 4 members), authors, labels, genres, sources (only if the group has 4 members). All tables should have all columns corresponding to the properties from the class diagram. Ensure that all foreign keys were set up correctly and that they have corresponding indexes.

2021-10-27 16:40 UTC, miguelesco commented
> > I really don't understand what you mean. I know this is not your fault, and we are probably just going to do what you suggested, but I'm really mad at Microverse, they always do this, but different things on the project requirements and in the code review guidelines. ![image](https://user-images.githubusercontent.com/73256642/138972714-b61121e4-5856-4b33-b6f4-7cc820357978.png)
> 
> * [x]  This was not implemented. Kindly create a schema.sql file that has the following tables: books,music_albums, games, movies (only if the group has 4 members), authors, labels, genres, sources (only if the group has 4 members). All tables should have all columns corresponding to the properties from the class diagram. Ensure that all foreign keys were set up correctly and that they have corresponding indexes.

in the route src/database/schema.sql there it is this problem solve

2021-10-27 23:20 UTC, oxenprogrammer approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-28 16:39 UTC, merged